# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-22 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='message',
            new_name='message_in_comments',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='message_in_messages',
        ),
    ]
