# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-23 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_and_reg_app', '0001_initial'),
        ('wall_app', '0003_auto_20190522_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='likes_on_message',
            field=models.ManyToManyField(related_name='message_user_liked', to='log_and_reg_app.Users'),
        ),
    ]
