# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-23 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_and_reg_app', '0001_initial'),
        ('wall_app', '0004_messages_likes_on_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='likes_on_comment',
            field=models.ManyToManyField(related_name='comment_user_liked', to='log_and_reg_app.Users'),
        ),
    ]
